CREATE TABLE fundata_full (
	FUNDATA_KEY int NOT NULL,
	START_DATE char(15) NOT NULL,
	ENGLISH_LEGAL_NAME char(150) NOT NULL,
	FRENCH_LEGAL_NAME char(150) NOT NULL,
	ENGLISH_FUND_NAME50 char(50) NOT NULL,
	FRENCH_FUND_NAME50 char(50) NOT NULL,
	ENGLISH_FUND_NAME25 char(25) NOT NULL,
	FRENCH_FUND_NAME25 char(25) NOT NULL,
	FUND_GRADE char(1),
	ASSOCIATED_BENCHMARK_ID int,
	ENGLISH_GROUP_NAME char(53) NOT NULL,
	FRENCH_GROUP_NAME char(59) NOT NULL,
	ENGLISH_FUND_TYPE_NAME char(41) NOT NULL,
	FRENCH_FUND_TYPE_NAME char(45) NOT NULL,
	ENGLISH_INVESTMENT_OBJECTIVE text(500),
	FRENCH_INVESTMENT_OBJECTIVE text(500),
	ENGLISH_INVESTMENT_STRATEGY text(500),
	FRENCH_INVESTMENT_STRATEGY text(500),
	ENGLISH_CLASSIFICATION char(10),
	FRENCH_CLASSIFICATION char(14),
	ENGLISH_DETAILED_CLASSIFICATION char(20),
	FRENCH_DETAILED_CLASSIFICATION char(30),
	RRSP_MIN_INVEST int,
	NON_RRSP_MIN_INVEST int,
	ENGLISH_LEGAL_STATUS char(15),
	FRENCH_LEGAL_STATUS char(15),
	ENGLISH_TRUST_TYPE char(10),
	FRENCH_TRUST_TYPE char(8),
	CURRENCY char(3) NOT NULL,
	ENGLISH_HOW_SOLD char(25),
	FRENCH_HOW_SOLD char(20),
	RRSP_ELIGIBLE char(3),
	RESP_ELIGIBLE char(1) NOT NULL,
	MER decimal(16,3),
	MGMT_FEE_PERCENT decimal(16,3),
	ENGLISH_MGMT_FEE_PAID_BY char(7),
	FRENCH_MGMT_FEE_PAID_BY char(10),
	TOTAL_ASSETS decimal(16,6),
	AVAILABLE_IN_PROVINCE char(39),
	ENGLISH_PROSPECTUS_RISK_RATING char(19),
	FRENCH_PROSPECTUS_RISK_RATING char(21),
	ENGLISH_PROSPECTUS_RISK text(1000),
	FRENCH_PROSPECTUS_RISK text(1000),
	VALUATION_FREQUENCY char(19) NOT NULL,
	DISTRIBUTION_FREQUENCY char(15) NOT NULL,
	MONEY_FUND char(1) NOT NULL,
	ENGLISH_CONCISE_FUND_OBJECTIVE char(0),
	FRENCH_CONCISE_FUND_OBJECTIVE char(0),
	TIME_HORIZON char(0)
) DEFAULT CHARSET = utf8;

CREATE TABLE fundata_fundserv_full (
	FUNDATA_KEY int NOT NULL,
	FUNDSERV_CODE char(12) NOT NULL,
	LOAD_TYPE char(50) NOT NULL,
	SERVICE_FEE_RATE char(10),
	SERVICE_FEE_FREQUENCY char(10)
) DEFAULT CHARSET = utf8;

CREATE TABLE fundata_allocation_full (
	FUNDATA_KEY int NOT NULL,
	AS_OF_DATE char(10) NOT NULL,
	PERCENT decimal(16,3) NOT NULL,
	DESCRIPTION char(50) NOT NULL,
	TYPE_DESCRIPTION char(50) NOT NULL
) DEFAULT CHARSET = utf8;

CREATE TABLE fundata_distribution_details_full (
	FUNDATA_KEY int NOT NULL,
	AS_OF_DATE char(10) NOT NULL,
	TOTAL_DIST_CURR_MTH decimal(12,10),
	TOTAL_DIST_YTD decimal(12,10),
	TOTAL_DIST_12MTH decimal(12,10),
	DIST_YIELD decimal(14,10),
	DIV_DIST_CURR_MTH decimal(12,10),
	DIV_DIST_YTD decimal(12,10),
	DIV_DIST_12MTH decimal(12,10),
	FGN_DIV_DIST_CURR_MTH decimal(12,10),
	FGN_DIV_DIST_YTD decimal(12,10),
	FGN_DIV_DIST_12MTH decimal(12,10),
	CAP_GAINS_DIST_CURR_MTH decimal(12,10),
	CAP_GAINS_DIST_YTD decimal(12,10),
	CAP_GAINS_DIST_12MTH decimal(12,10),
	INT_INC_DIST_CURR_MTH decimal(12,10),
	INT_INC_DIST_YTD decimal(12,10),
	INT_INT_DIST_12MTH decimal(12,10),
	RTN_PRINCIPLE_CURR_MTH decimal(12,10),
	RTN_PRINCIPLE_YTD decimal(12,10),
	RTN_PRINCIPLE_12MTH decimal(12,10),
	DIST_FREQ char(16) NOT NULL
) DEFAULT CHARSET = utf8;

CREATE TABLE fundata_fees_full (
	FUNDATA_KEY int NOT NULL,
	RRSP_ANNUAL_ADMIN_FEES int,
	RRIF_ANNUAL_ADMIN_FEES int,
	ENGLISH_SWITCH_FEES char(250),
	FRENCH_SWITCH_FEES char(80),
	RRSP_WITHDRAWAL_FEES decimal(6,3),
	RRIF_WITHDRAWAL_FEES decimal(6,3),
	ENGLISH_TRAILER_FEES char(80),
	FRENCH_TRAILER_FEES char(80),
	PAC_PLAN char(1),
	SWP_PLAN char(1),
	SWP_MIN_BALANCE int,
	ENGLISH_LOAD char(26),
	FRENCH_LOAD char(28),
	NO_LOAD_FUND char(1),
	CHOICE_OF_FRONT_OR_BACK_FEE char(1),
	MAX_FRONT_END_PERCENT decimal(6,3),
	MAX_BACK_END_PERCENT decimal(6,3),
	ENGLISH_BACK_END_FEE_APP_TO char(25),
	FRENCH_BACK_END_FEE_APP_TO char(25)
) DEFAULT CHARSET = utf8;

CREATE TABLE fundata_fundbenchmarks_full (
	FUNDATA_KEY int NOT NULL,
	ENGLISH_FUND_NAME_50 char(100) NOT NULL,
	FRENCH_FUND_NAME_50 char(100) NOT NULL,
	ASSOCIATED_BENCHMARK_ID int,
	ENGLISH_FUND_TYPE_NAME char(50) NOT NULL
) DEFAULT CHARSET = utf8;

CREATE TABLE fundata_fundcompanies_full (
	FUNDATA_KEY int NOT NULL,
	ENGLISH_MSTR_GRP_NAME char(100) NOT NULL,
	FRENCH_MSTR_GRP_NAME char(100) NOT NULL,
	ENGLISH_GRP_NAME char(100) NOT NULL,
	FRENCH_GRP_NAME char(100) NOT NULL,
	ADDRESS char(150),
	TELEPHONE char(20),
	WEBSITE char(100),
	IFIC_MEMBER_STATUS char(1) NOT NULL
) DEFAULT CHARSET = utf8;

CREATE TABLE fundata_managers_full (
	FUNDATA_KEY int NOT NULL,
	MANAGER_NAME char(60),
	MANAGER_TITLE char(30),
	ENGLISH_MANAGER_BIO text(300),
	FRENCH_MANAGER_BIO text(300),
	START_DATE char(10) NOT NULL,
	EXPERIENCE char(30),
	COMPANY char(50)
) DEFAULT CHARSET = utf8;

CREATE TABLE fundata_monthlypricing_full (
	FUNDATA_KEY int NOT NULL,
	AS_OF_DATE char(10),
	NAVPS decimal(18,8),
	MER decimal(7,4),
	TOTAL_ASSETS decimal(16,8),
	DIVIDEND_INCOME decimal(18,9),
	CAPITAL_GAINS decimal(18,9),
	RETURN_OF_CAPITAL decimal(15,6),
	DISTRIBUTION_TOTAL decimal(18,9),
	SPLIT_FACTOR int,
	DISTRIBUTION_FREQUENCY char(20)
) DEFAULT CHARSET = utf8;

CREATE TABLE fundata_performance_full (
	FUNDATA_KEY int NOT NULL,
	AS_OF_DATE char(10) NOT NULL,
	1MTH_RETURN decimal(7,4),
	3MTH_RETURN decimal(7,4),
	6MTH_RETRUN decimal(7,4),
	YTD_RETURN decimal(7,4),
	1YR_SIMPLE_RETURN decimal(7,4),
	3YR_SIMPLE_RETURN decimal(7,4),
	5YR_SIMPLE_RETURN decimal(7,4),
	10YR_SIMPLE_RETURN decimal(7,4),
	1YR_COMPOUND_RETURN decimal(7,4),
	3YR_COMPOUND_RETURN decimal(7,4),
	5YR_COMPOUND_RETURN decimal(7,4),
	10YR_COMPOUND_RETURN decimal(7,4),
	INCEPTION_RETURN decimal(7,4) NOT NULL,
	TOTAL_DIST decimal(10,7),
	DIST_YIELD decimal(8,4)
) DEFAULT CHARSET = utf8;

CREATE TABLE fundata_portfoliodetails_full (
	FUNDATA_KEY int NOT NULL,
	DATE char(10) NOT NULL,
	STYLE_BIAS char(6),
	MKT_CAP_BIAS char(6),
	MOD_DURATION_DATE char(10),
	MOD_DURATION decimal(9,6),
	AVG_MATURITY decimal(4,2),
	SHORT_TERM_BOND decimal(6,3),
	MID_TERM_BOND decimal(6,3),
	LONG_TERM_BOND decimal(6,3),
	AS_OF_DATE char(10),
	CREDIT_RATING int
) DEFAULT CHARSET = utf8;

CREATE TABLE fundata_riskreturn_full (
	FUNDATA_KEY int NOT NULL,
	AS_OF_DATE char(10) NOT NULL,
	YEAR int NOT NULL,
	BENCHMARK_ID int,
	ALPHA decimal(9,6),
	BETA decimal(8,5),
	SHARPE decimal(10,5),
	TREYNOR decimal(10,5),
	RSQUARED decimal(7,5),
	SORTINO decimal(9,6),
	STDDEV decimal(8,6),
	VOLATILITY int,
	BENCHMARK_CORRELATION decimal(7, 4)
) DEFAULT CHARSET = utf8;

CREATE TABLE fundata_servicecompanies_full (
	FUNDATA_KEY int NOT NULL,
	SERVICE_COMPANY_TYPE char(30),
	COMPANY_NAME char(55) NOT NULL,
	ADDRESS char(95)
) DEFAULT CHARSET = utf8;

CREATE TABLE fundata_topholdings_full (
	FUNDATA_KEY int NOT NULL,
	DATE char(10) NOT NULL,
	RANK_ORDER int NOT NULL,
	SECURITY_ID int NOT NULL,
	SECURITY_NAME char(85) NOT NULL,
	SECURITY_NAME_FRENCH char(60),
	MARKET_PERCENT decimal(6,2) NOT NULL
) DEFAULT CHARSET = utf8;

CREATE TABLE fundata_yearperformance_full (
	FUNDATA_KEY int NOT NULL,
	AS_OF_DATE char(10) NOT NULL,
	YEAR int NOT NULL,
	SIMPLE_RETURN decimal(7,3) NOT NULL,
	SIMPLE_RANK int,
	SIMPLE_RANK_COUNT int NOT NULL,
	SIMPLE_QUARTILE int,
	COMPOUND_RETURN decimal(7,3),
	COMPOUND_RANK int,
	COMPOUND_RANK_COUNT int NOT NULL,
	COMPOUND_QUARTILE int,
	CALENDAR_SIMPLE_RTN decimal(7,3),
	CALENDAR_SIMPLE_RANK int,
	CALENDAR_SIMPLE_RANK_COUNT int NOT NULL,
	CALENDAR_SIMPLE_QUARTILE int,
	CALENDAR_COMPOUND_RTN decimal(7,3),
	CALENDAR_COMPOUND_RANK int,
	CALENDAR_COMPOUND_RANK_COUNT int NOT NULL,
	CALENDAR_COMPOUND_QUARTILE int
) DEFAULT CHARSET = utf8;