CREATE TABLE FSRV_PROD (
    FSRV_ID int NOT NULL auto_increment,
    MGMT_CODE char(3) NOT NULL,
    EFF_DT date NOT NULL,
    FUND_ID char(5) NOT NULL,
    FUND_LINK_ID char(5) NOT NULL,
    CUT_OFF_TIME time NOT NULL,
    CUSIP char(9),
    ISIN char(12),
    MGMT_CO_BRAND_NM char(7) NOT NULL,
    ENG_SHORT_NM char(20) NOT NULL,
    ENG_LONG_NM char(80) NOT NULL,
    FRE_SHORT_NM char(20) NOT NULL,
    FRE_LONG_NM char(80) NOT NULL,
    PROD_TYPE char(1) NOT NULL,
    CURR char(2) NOT NULL,
    LOAD_TYPE char(4) NOT NULL,
    CLASSIFICATION char(2),
    TAX_STRUCT char(1) NOT NULL,
    MM_FLAG char(1) NOT NULL,
    BARE_TRUSTEE_FLAG char(1) NOT NULL,
    RISK_CLASS char(1) NOT NULL,
    ACCT_SETUP_FEE decimal(16,2) NOT NULL,
    SERV_FEE_RATE decimal(16,3) NOT NULL,
    SERV_FEE_FREQ char(1) NOT NULL,
    DSC decimal(16,3),
    DSC_DURATION int,
    MAX_COMM decimal(16,3) NOT NULL,
    MAX_SW_COMM decimal(16,3) NOT NULL,
    NEGOT_FEE char(1),
    NEGOT_TRAILER char(1),
    FEE_BASED_ELIG char(1),
    SERIES char(5),
    CLASS char(5),
    SER_CLASS_SEQ_IN_NAME char(2),
    BRAND char(15),
    DISC_BROKER_ONLY char(1),
    REG_DOC_TYPE char(1) NOT NULL,
    ELIG_US char(1) NOT NULL,
    ELIG_OFFSHORE char(1) NOT NULL,
    ELIG_PAC char(1) NOT NULL,
    ELIG_SWP char(1) NOT NULL,
    PRIMARY KEY(FSRV_ID)
) DEFAULT CHARSET = utf8;
CREATE INDEX idx_MGMT_CODE_FUND_ID ON fsrv_prod(MGMT_CODE, FUND_ID);
CREATE INDEX idx_PROD_TYPE ON fsrv_prod(PROD_TYPE);
CREATE INDEX idx_LOAD_TYPE ON fsrv_prod(LOAD_TYPE);
CREATE INDEX idx_CLASSIFICATION ON fsrv_prod(CLASSIFICATION);
CREATE INDEX idx_RISK_CLASS ON fsrv_prod(RISK_CLASS);

CREATE TABLE FSRV_MINS (
    SEQ_ID int NOT NULL,
    MIN_FIRST decimal(16,2) NOT NULL,
    MIN_NXT decimal(16,2) NOT NULL,
    MIN_SELL decimal(16,2) NOT NULL,
    MIN_SW decimal(16,2) NOT NULL,
    MIN_TRSF decimal(16,2) NOT NULL,
    MIN_BAL decimal(16,2) NOT NULL,
    MIN_PAC decimal(16,2) NOT NULL,
    MIN_SWP decimal(16,2) NOT NULL, 
    FOREIGN KEY (SEQ_ID) REFERENCES FSRV_PROD(FSRV_ID)
) DEFAULT CHARSET = utf8;

CREATE TABLE FSRV_ELIG_PROV(
    SEQ_ID int NOT NULL,
    PROV_STATE char(2) NOT NULL,
    FOREIGN KEY (SEQ_ID) REFERENCES FSRV_prod(FSRV_ID)
) DEFAULT CHARSET = utf8;

CREATE TABLE FSRV_ELIG_TRXN (
    SEQ_ID int NOT NULL,
    TRXN_TYPE char(2) NOT NULL,
    TRXN_STATUS char(1) NOT NULL,
    FOREIGN KEY (SEQ_ID) REFERENCES FSRV_PROD(FSRV_ID)
) DEFAULT CHARSET = utf8;

CREATE TABLE FSRV_ELIG_ACCT_TYPES (
    SEQ_ID int NOT NULL,
    DESIGNATION char(1) NOT NULL,
    ACCT_TYPE char(3) NOT NULL,
    FOREIGN KEY (SEQ_ID) REFERENCES FSRV_PROD(FSRV_ID)
) DEFAULT CHARSET = utf8;
CREATE INDEX idx_designation ON FSRV_ELIG_ACCT_TYPES(DESIGNATION);

CREATE TABLE FSRV_ELIG_DIV_OPT (
    SEQ_ID int NOT NULL,
    DIV_FREQ char(1) NOT NULL,
    DIV_OPT_1 char(1) NOT NULL,
    DIV_OPT_4 char(1) NOT NULL,
    DIV_OPT_5 char(1) NOT NULL,
    FOREIGN KEY (SEQ_ID) REFERENCES FSRV_PROD(FSRV_ID)
) DEFAULT CHARSET = utf8;

CREATE TABLE FSRV_PROD_MODEL (
    SEQ_ID int NOT NULL,
    TYPE char(6) NOT NULL,
    FREQ char(1) NOT NULL,
    SETTLE_PERIOD int NOT NULL,
    FOREIGN KEY (SEQ_ID) REFERENCES FSRV_PROD(FSRV_ID)
) DEFAULT CHARSET = utf8;